import { Card, CardContent, CardHeader, CardTitle } from '@/app/components/Card';
import { RunNameField } from '@/app/components/export/RunNameField';

interface StepOptionsProps {
  runName: string;
  setRunName: (value: string) => void;
  outputDir: string;
  setOutputDir: (value: string) => void;
  downloadAssets: boolean;
  setDownloadAssets: (value: boolean) => void;
  maxCharsPerFile: string;
  setMaxCharsPerFile: (value: string) => void;
  onContinue: () => void;
}

export function StepOptions({
  runName,
  setRunName,
  outputDir,
  setOutputDir,
  downloadAssets,
  setDownloadAssets,
  maxCharsPerFile,
  setMaxCharsPerFile,
  onContinue,
}: StepOptionsProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Step 3: Options</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <RunNameField value={runName} onChange={setRunName} provider="confluence" />

          <div>
            <label
              htmlFor="outputDir"
              className="mb-2 block text-sm font-medium text-zinc-700 dark:text-zinc-300"
            >
              Base Output Directory
            </label>
            <input
              id="outputDir"
              type="text"
              value={outputDir}
              onChange={(e) => setOutputDir(e.target.value)}
              className="w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"
              placeholder="./exports"
            />
            <p className="mt-1 text-xs text-zinc-500">
              Files will be saved to: {outputDir}/confluence/{runName || '<auto-generated>'}
            </p>
          </div>

          <div className="flex items-center justify-between rounded-md border border-zinc-200 bg-zinc-50 px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950">
            <div>
              <label htmlFor="downloadAssets" className="font-medium text-zinc-900 dark:text-zinc-100">
                Download assets
              </label>
              <p className="text-sm text-zinc-600 dark:text-zinc-400">
                Download images and attachments locally (not yet implemented)
              </p>
            </div>
            <input
              id="downloadAssets"
              type="checkbox"
              checked={downloadAssets}
              onChange={(e) => setDownloadAssets(e.target.checked)}
              disabled
              className="h-4 w-4 rounded border-zinc-300 text-blue-600 focus:ring-blue-500 disabled:cursor-not-allowed disabled:opacity-50"
            />
          </div>

          <div>
            <label
              htmlFor="maxCharsPerFile"
              className="mb-2 block text-sm font-medium text-zinc-700 dark:text-zinc-300"
            >
              Max Characters Per File (optional)
            </label>
            <input
              id="maxCharsPerFile"
              type="number"
              value={maxCharsPerFile}
              onChange={(e) => setMaxCharsPerFile(e.target.value)}
              className="w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"
              placeholder="Leave empty for unlimited"
            />
            <p className="mt-1 text-xs text-zinc-500">
              Split large pages into multiple files (e.g., 50000)
            </p>
          </div>

          <button
            onClick={onContinue}
            className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            Continue to Run Export
          </button>
        </div>
      </CardContent>
    </Card>
  );
}
